# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0006_auto_20220817_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(default=True, max_length=16),
            preserve_default=False,
        ),
    ]
