# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0007_user_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=16, primary_key=True),
        ),
    ]
