# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0008_auto_20220818_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
