# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0010_auto_20220818_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='approval_status',
            new_name='book_approval_status',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('ebook', 'ebook'), ('nbook', 'hardcopy of the book')], max_length=50),
        ),
    ]
