# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-18 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0011_auto_20220818_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='book_approval_status',
            new_name='approval_status',
        ),
    ]
